DROP TABLE users IF EXISTS;
DROP TABLE cafes IF EXISTS;
DROP TABLE menu  IF EXISTS;
DROP TABLE vote  IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    login            VARCHAR(255)            NOT NULL,
    password         VARCHAR(255)            NOT NULL,
    role             VARCHAR(255)            NOT NULL,
    ACTIVE           BOOLEAN                 default true
);
CREATE UNIQUE INDEX users_unique_login_idx
    ON USERS (login);

CREATE TABLE cafes
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)            NOT NULL,
    menu_id          INTEGER                 NOT NULL
);

CREATE TABLE menu
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name_first             VARCHAR(255)            NOT NULL,
    price_first            INTEGER                 NOT NULL,
    name_second            VARCHAR(255)            NOT NULL,
    price_second           INTEGER                 NOT NULL,
    name_dessert           VARCHAR(255)            NOT NULL,
    price_dessert          INTEGER                 NOT NULL,
    name_drink             VARCHAR(255)            NOT NULL,
    price_drink            INTEGER                 NOT NULL
);

CREATE TABLE vote
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    user_id                 INTEGER                 NOT NULL,
    cafe_id                 INTEGER                 NOT NULL,
    time_vote               TIMESTAMP               NOT NULL
);
